//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saml
    {
        public int id { get; set; }
        public string username { get; set; }
        public string domain { get; set; }
        public Nullable<System.DateTime> loginDate { get; set; }
        public Nullable<System.DateTime> logoutDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Issuer { get; set; }
        public string Audience { get; set; }
        public string Subject { get; set; }
        public string Recipient { get; set; }
        public string ResponseID { get; set; }
        public string Status { get; set; }
        public string AssertionID { get; set; }
        public string SamlStartDate { get; set; }
        public string SamlEndDate { get; set; }
    }
}
